### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by brandelune** [OmegaT-L10N/ja#14]
形式的な変更をこちらで対応しましたが、テーマについて分節が４つ残っています。
あと、「brandelune」が今日やったことも目を通してください！

**Comment by miurahr** [comment]
> Restart OmegaT to apply these changes
> 変更を適用するために再起動が必要

>Reload the current project to apply these changes
>変更を適用するためにプロジェクトの再読み込みが必要

日本語の表現も、見なおすとよいとおもいます。

Proposal1

- 再起動して変更を適用してください
- プロジェクトを再読み込みし変更を適用してください

proposal2

- 変更の適用には再起動が必要
- 変更の適用にはプロジェクトの再読み込みが必要

**Comment by brandelune** [comment]
ご確認ありがとうございました。ネイティブではない私は、proposal 2がいいと思います。
または：
変更の適用には再起動が必要
→
変更の適用にはOmegaTの再起動が必要
（場合によって、OSと勘違いする人もいたりするので）

**Comment by miurahr** [comment]
Theme 4つの訳をいれました
