### ISSUE TITLE
NICT Textra グループによる機械翻訳精度をたかめる提案

### ISSUE THREAD

**Issue by miurahr** [OmegaT-L10N/ja#5]
NICTのＴｅｘｔｒａは、OSS翻訳を明示的に許諾しています。また、Group機能があり、共通のTranslation memory(TMX)と Glossary(tsv)をアップロードすることで、機械翻訳エンジンをカスタマイズする機能があります。

そこで、本翻訳チームのグループをTextraに定義し、本リポジトリの翻訳メモリとglossaryをアップロードし、共通のTextra engineをつかって翻訳することで、翻訳精度を高める提案をします。

Textra MT engine powered by NICT is EXPLICITLY PERMIT translation for OSS product and documdntations even it limit its usage for non-profit and many other conditions.
It has a group feature to allow translators make group and share the engine configuration with TM and Glossary data.

I'd like to propose to create a group on TexTra site and upload tmx and glossary.txt to TexTra then use common engine to improve MT results.

**Comment by miurahr** [comment]
@yu-tang この試みに参加してもらえませんか？

**Comment by yu-tang** [comment]
Textra はあんまり有効活用している話を聞かず、もったいないなあとは思っていたので、ご提案はすばらしいと思います。
参加するのは問題ないですが、自分自身があんまり翻訳作業してないので（いまだに苦手です）、実作業のアクティビティーが出せるかというと、かなりアヤシイです。
いいね職人的なスタンスでよければ、参加します（いいわけないよなーと思いながら書いてます、ゴメン）。

**Comment by miurahr** [comment]
メンバーが複数名いないと、TexTraにグループがつくれなくて、動作検証にならないのですよ。また、OmegaTコミュニティに共有できる実績、事例づくりの意味合いもあります。

**Comment by miurahr** [comment]
カスタム翻訳エンジンを作成しました。

Key, Secretは、メールしたID, PASSを使用して確認し、利用してください。
OmegaT-textra-pluginは、まだカスタム設定に対応していません。

![image](https://user-images.githubusercontent.com/123720/99160050-497b7400-2726-11eb-8235-c71210fbe2e5.png)

![image](https://user-images.githubusercontent.com/123720/99160067-69129c80-2726-11eb-86bf-355f2a32053e.png)

**Comment by miurahr** [comment]
一般翻訳者だと、WebAPIの表示画面がでませんでした。 そのため、 omegat2jaユーザとしてログインして、APIの key secretを確認する必要があります。

**Comment by miurahr** [comment]
https://github.com/miurahr/omegat-textra-plugin/releases
OmegaT TexTra plugin v2020.1.1 で、カスタムエンジンの利用ができるようにしました。

**Comment by miurahr** [comment]
https://github.com/miurahr/omegat-textra-plugin/releases/tag/v2020.2.0
OmegaT textra plugin を更新し、カスタム翻訳エンジンがつかえるようにしました。
設定で、カスタム翻訳エンジンの入力欄に **c-1439** と入力します。 キーやシークレットなどの確認は、 omegat2ja ユーザで実施してください。そして、 UserID には、omegat2ja  Key: 49............  Secret:......d1  を入力してください。

 用語集と既存のTMXをアップロードしているため、精度の高い翻訳を得られるはずです。
