### ISSUE TITLE
Proposal: Change "aligner" / 訳語の変更提案

### ISSUE THREAD

**Issue by miurahr** [OmegaT-L10N/ja#6]
There are terms "Aligner" and "Alignment"  are translated into "整列" currently.
The menu item "Align Files..." becomes "ファイルの整列..." but it is not good explains its feature.

In glossary it defined as "Undecided and temporary"
```
align = 整列
1. 未討議。一貫性を確保するため、とりあえずこの訳語で登録しておきます。
```

用例辞書を確認すると、alignerは
◆ a mask aligner　《半導体》マスクアライナー 
の用例があり、

"alignment"  には
 アライメント, アラインメント, 整列, 配列, 並び, 配向, 調整, 整合, 心合わせ, 調芯, 位置合わせ, 位置揃え, 位置調整, 位置詰め, 位置寄せ, (意訳) ずれをなくすための調整; 連合（すること）
の候補があります。

光ファイバにおける調芯のような確立した用語がまだ無いため、定義をする必要があるとおもいます。TexTraではTMXのことを「対訳集」と呼称しています。

特定のOmegaT機能の名称であるため、意訳をふくめて、「対訳集位置あわせツール」 への変更を提案します。

**Comment by yu-tang** [comment]
変更には異論ありません。
ただ翻訳支援ツールの業界には業界用語としての定訳が存在する場合があるので、そこは抑えておいたほうが無難かなとは思います。
プロプライエタリの翻訳支援ツールとしては、たぶん Trados と MemoQ が有名です（他にもいろいろありますが）。
私はこの2つとも使ったことがないので（プロではないので）直接は知らないのですが、たしか両方とも Alignment を「整合」とか「整合機能」みたいな呼び方をしていたはず。ということは、日本の翻訳者のあいだでは「整合」がこの機能に対する事実上の定訳になっている可能性が高いです。これ自分も確信があるわけではないので、三浦さんの側でも確認していただけると有り難いです。

**Comment by miurahr** [comment]
https://www.sdltrados.com/jp/solutions/translation-alignment/

> 翻訳の整合とは？
> 翻訳の整合とは、既存の翻訳資料を活用する1つの手法です。

> 翻訳整合ツール

> 整合ツールを使用して、原文ファイルと訳文ファイルを並列にし、対になる組み合わせを決定します。


これっすね。

**Comment by miurahr** [comment]
https://www.memoq.com/ja/products/memoq-translator-pro

> 文書のペアが追加されると、memoQはすぐにそれらを整合し、整合された文書から一致項目を提示します。 ライブ文書ではバイリンガルファイルも翻訳メモリとして使用でき、文書全体のプレビュー表示や文脈の確認にも使えます。

**Comment by miurahr** [comment]
**整合** を採用しようとおもいます。

**Comment by miurahr** [comment]
いったん、整合を採用しましたが、NICTでは、 対訳アライメント とよんでいるようです。

![image](https://user-images.githubusercontent.com/123720/99216367-d868b900-2818-11eb-80b1-28d6e93dcfa6.png)

**Comment by yu-tang** [comment]
へー。なるほど。まあ、伝われば何でもいいです。
商用プロダクトの場合は、試用したときに用語の違いがストレスになって他社ユーザーに乗り換えてもらえないのを嫌うので、だいたい大手の用語で統一されちゃう傾向はありますね。

余談ですけど、OmegaT を最初に日本語化したときはカタカナ語を徹底的に避けるという方針があったらしくて（当時は自分はいないので、状況がよく分からないのですが）、それが現在の日本語版のベースになっています。
その後、自分が参加した時には割りと自由にやったので、あるていどカタカナ語も使ったんですが、あくまで未訳をつぶすのが優先だったので、訳語統一の問題がない限りは既存訳にあまりさわりませんでした。
今はもう、カタカナ語を避けると逆に不自然になるケースが多いので、自由にやっていいんじゃないでしょうか。まあやりすぎると、意識高い系社長の挨拶文みたいになるので、加減が大事ですけど。

**Comment by miurahr** [comment]
重要な決定については、できれば、今回のようにissueをあげて検討プロセスを記録にのこして、あとでなぜそうなったか、を将来の翻訳者が確認できるようになっていることが、ベターだとおもいます。OmegaTのチーム機能では、メモをのこすことができますが、みやすいのはIssueです。
 あと、折角チーム活動なので、ソロでなくて、やりとりがあったほうが、モチベーションの維持にやくだちます。

**Comment by miurahr** [comment]
alignerの訳語について、訳書「機械翻訳(Thierry Poibeau著)」では、訳者の高橋氏は、つぎのように訳出しています。

- sentence alignment  = 文アラインメント
- "align" = 「アライン(整合)する」

工夫と苦労がよみとれます。。
